FROM node:18-alpine
WORKDIR /app

# 개발용 의존성 포함
COPY package.json package-lock.json ./
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm install  # devDependencies 포함

COPY . .

CMD ["npm", "run", "dev"]
