services:

  api-gateway:
    image: api-gateway:dev
    build:
      # context: ./spring-app/api-gateway/
      # dockerfile: ./Dockerfile
      context: ./spring-app
      dockerfile: ./Dockerfile-api-gateway
    restart: always
    ports:
      - "9999:9999"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: 9999
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      AUTH_SERVICE_URI: ${AUTH_SERVICE_URI}
      ALCOHOL_SERVICE_URI: ${ALCOHOL_SERVICE_URI}
      HIGHBALL_SERVICE_URI: ${HIGHBALL_SERVICE_URI}
      REVIEW_SERVICE_URI: ${REVIEW_SERVICE_URI}
      PAIRING_SERVICE_URI: ${PAIRING_SERVICE_URI}
    volumes:
      - ./spring-app/api-gateway/build:/app/api-gateway/build
      - ./spring-app/api-gateway/src:/app/api-gateway/src
    networks:
      - dlink_net

  auth-service:
    image: auth-service:dev
    build:
      context: ./spring-app
      dockerfile: ./Dockerfile-auth
    restart: always
    ports:
      - "9991:9991"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      NEXT_URI: ${NEXT_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SERVER_PORT: 9991
    volumes:
      - ./spring-app/auth/build:/app/auth/build
      - ./spring-app/auth/src:/app/auth/src
    networks:
      - dlink_net

  alcohol-service:
    image: alcohol-service:dev
    build:
      context: ./spring-app/
      dockerfile: ./Dockerfile-alcohol
    restart: always
    ports:
      - "9992:9992"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      ES_DATASOURCE_URI: ${ES_DATASOURCE_URI}
      SERVER_PORT: 9992
    volumes:
      - ./spring-app/alcohols/build:/app/alcohols/build
      - ./spring-app/alcohols/src:/app/alcohols/src
    networks:
      - dlink_net

  highball-service:
    image: highball-service:dev
    build:
      context: ./spring-app/
      dockerfile: ./Dockerfile-highball
    restart: always
    ports:
      - "9993:9993"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      SERVER_PORT: 9993
    volumes:
      - ./spring-app/highball/build:/app/highball/build
      - ./spring-app/highball/src:/app/highball/src
    networks:
      - dlink_net

  review-service:
    image: review-service:dev
    build:
      context: ./spring-app/
      dockerfile: ./Dockerfile-review
    restart: always
    ports:
      - "9994:9994"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SERVER_PORT: 9994
    volumes:
      - ./spring-app/review/build:/app/review/build
      - ./spring-app/review/src:/app/review/src
    networks:
      - dlink_net

  pairing-service:
    image: pairing-service:dev
    build:
      context: ./spring-app/
      dockerfile: ./Dockerfile-pairing
    restart: always
    ports:
      - "9995:9995"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      SERVER_PORT: 9995
    volumes:
      - ./spring-app/pairing/build:/app/pairing/build
      - ./spring-app/pairing/src:/app/pairing/src
    networks:
      - dlink_net

  next-app:
    image: next-app:dev
    build:
      context: ./next-app/
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      KAKAO_REST_API: ${KAKAO_REST_API}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
      NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      SPRING_URI: ${SPRING_URI}
    networks:
      - dlink_net
    volumes:
      - ./next-app:/app

networks:
  dlink_net:
