services:

  zookeeper:
    image: bitnami/zookeeper:latest
    networks:
      - kafka_net
    container_name: zookeeper
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    build:
      context: ./kafka/broker  # 빌드할 Dockerfile이 있는 경로
      dockerfile: Dockerfile
    container_name: kafka-broker-1
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - BROKER_ID=1
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ADVERTISED_LISTENERS=PLAINTEXT://192.168.3.81:9092
      - LOG_DIRS=/var/lib/kafka/logs-1
    volumes: 
      - ./kafka/logs-1:/var/lib/kafka/logs-1
    ports:
      - "9092:9092"
    networks:
      - kafka_net
    restart: unless-stopped

networks:
  kafka_net:
    driver: bridge

