services:

  api-gateway:
    image: api-gateway:dev
    build:
      context: ./spring-app
      dockerfile: ./Dockerfile-api-gateway
    restart: always
    ports:
      - "9990:9990"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_SERVER_PORT: 9990
      NEXT_URI: ${NEXT_URI}
    volumes:
      - ./spring-app/api-gateway/build:/app/api-gateway/build
      - ./spring-app/api-gateway/src:/app/api-gateway/src
    networks:
      - dlink_net

  auth-service:
    image: auth-service:dev
    build:
      context: ./spring-app
      dockerfile: ./Dockerfile-auth
    restart: always
    ports:
      - "9991:9991"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_SERVER_PORT: 9991
      SPRING_DATASOURCE_URI: ${SPRING_DATASOURCE_URI}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    volumes:
      - ./spring-app/auth/build:/app/auth/build
      - ./spring-app/auth/src:/app/auth/src
    networks:
      - dlink_net

  next-app:
    image: next-app:dev
    build:
      context: ./next-app/
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      SPRING_URI: http://api-gateway:8080/
      NEXTAUTH_SECRET: ${JWT_SECRET_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    depends_on:
      - api-gateway
    networks:
      - dlink_net
    volumes:
      - ./next-app:/app

networks:
  dlink_net:
