spring:
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    # properties:
    #   hibernate:
    #     format_sql: true

springdoc:
  api-docs:
    path: /api/v1/auth/v3/api-docs

logging:
  level:
    root: INFO
    site:
      dlink:
        auth: DEBUG