spring:
  application:
    name: alcohols
  elasticsearch:
    uris: ${ES_DATASOURCE_URI:localhost:9200}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_APP_USERNAME}
    password: ${GOOGLE_APP_PASSWORD:ffffffffffffffff}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
