spring:
  application:
    name: auth

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    group:
      prod:
        - prod
      dev:
        - dev

  data:
    mongodb:
      uri: ${SPRING_DATASOURCE_URI}
