spring:
  application:
    name: auth

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    group:
      prod:
        - prod
      dev:
        - dev

  datasource:
    url: ${SPRING_DATASOURCE_URI}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}