FROM gradle:8.12.0-jdk21-alpine AS dev
WORKDIR /app

COPY build.gradle settings.gradle ./
COPY gradle ./gradle
RUN gradle build --no-daemon || return 0
COPY . .

CMD ["gradle", "bootRun", "--no-daemon"]
