spring:
  application:
    name: alcohols

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    group:
      prod:
        - prod
      dev:
        - dev

  datasource:
    url: mongodb://asordk.synology.me:27017/alcohol_db