spring:
  application:
    name: pairing
  ai:
    bedrock:
      aws:
        region: us-west-2
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      converse:
        chat:
          options:
            model: arn:aws:bedrock:us-west-2:084550838259:inference-profile/us.meta.llama3-3-70b-instruct-v1:0
            temperature: 0.7
            max-tokens: 500
