# Builder Stage
FROM gradle:8.12.0-jdk21-alpine AS builder
WORKDIR /app

# Gradle 캐싱 최적화
COPY gradle gradle
COPY gradlew gradlew
COPY build.gradle settings.gradle ./
RUN chmod +x gradlew

# 종속성 미리 다운로드하여 캐싱
RUN ./gradlew :pairing:dependencies --no-daemon

# 소스 코드 복사 및 빌드
COPY . .
RUN ./gradlew :pairing:bootJar --no-daemon

# 필수 패키지 설치 (Chromium & ChromeDriver 포함)
RUN apk update && apk add --no-cache \
    chromium \
    chromium-chromedriver \
    harfbuzz \
    nss \
    freetype \
    ttf-freefont \
    fontconfig \
    libstdc++ \
    bash \
    curl \
    wget \
    unzip \
    glib \
    xvfb

# 환경 변수 설정 (Selenium 사용을 위한 경로 지정)
ENV CHROME_BIN=/usr/bin/chromium
ENV CHROME_DRIVER=/usr/bin/chromedriver

# 실행 사용자 추가 (보안 강화)
RUN groupadd --system appgroup && useradd --system --create-home --gid appgroup appuser

# 애플리케이션 복사
COPY /app/build/libs/*.jar app.jar

# 소유권 변경 및 실행 권한 부여
RUN chown -R appuser:appgroup /app && chmod 750 /app/app.jar

USER appuser

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
