spring:
  application:
    name: highball

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

cloud:
  aws:
    s3:
      bucket: dlink-highball-bucket
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY:default-access-key}
      secret-key: ${AWS_SECRET_KEY:default-secret-key}
    region:
      static: ap-northeast-2

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0 
  zipkin:
    tracing:
      endpoint: ${OTEL_COLLECTOR_URI}