spring:
  devtools:
    restart:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# logging:
#   level:
#     org:
#       springframework: INFO
#       hibernate: INFO