name: CI Pipeline

on:
  push:
    branches:
      - ci-test  # ci-test 브랜치에 push되면 실행됨

jobs:
  build-backend:
    name: Build Spring Boot
    runs-on: self-hosted

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle 빌드
        run: |
          cd spring-app
          chmod +x gradlew
          ./gradlew build

  build-frontend:
    name: Build Next.js
    runs-on: self-hosted

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Next.js 빌드
        run: |
          cd next-app
          npm install
          npm run build

  docker-build-push:
    name: Build & Push Docker Images
    runs-on: self-hosted
    needs: [build-backend, build-frontend]

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: 태그 생성 (Git SHA + 날짜)
        id: vars
        run: |
          echo "TAG_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "TAG_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Docker 빌드 & 태깅
        run: |
          docker build -t 192.168.3.81/harbor/projects/3/repositories/dlink-backend:latest -t 192.168.3.81/harbor/projects/3/repositories/dlink-backend:${{ env.TAG_DATE }}-${{ env.TAG_SHA }} ./spring-app
          docker build -t 192.168.3.81/harbor/projects/3/repositories/dlink-frontend:latest -t 192.168.3.81/harbor/projects/3/repositories/dlink-frontend:${{ env.TAG_DATE }}-${{ env.TAG_SHA }} ./next-app

      - name: Harbor 로그인
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login 192.168.3.81 -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Docker 이미지 푸시
        run: |
          docker push 192.168.3.81/harbor/projects/3/repositories/dlink-backend:latest
          docker push 192.168.3.81/harbor/projects/3/repositories/dlink-backend:${{ env.TAG_DATE }}-${{ env.TAG_SHA }}
          docker push 192.168.3.81/harbor/projects/3/repositories/dlink-frontend:latest
          docker push 192.168.3.81/harbor/projects/3/repositories/dlink-frontend:${{ env.TAG_DATE }}-${{ env.TAG_SHA }}
