name: CI Pipeline for Docker & Harbor

on:
  push:
    branches:
      - ci-test  # ci-test 브랜치에 push 시 실행

jobs:
  build-and-push:
    runs-on: self-hosted  # GitHub Runner에서 실행됨

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull latest code
        run: git pull origin ci-test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login 192.168.3.81 -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker build -t 192.168.3.81/test/dlink:latest .
          docker push 192.168.3.81/test/dlink:latest

      - name: Deploy using Docker Compose
        run: |
          docker-compose -f docker-compose-01.yml down
          docker-compose -f docker-compose-01.yml up -d
          docker-compose -f docker-compose-02.yml down
          docker-compose -f docker-compose-02.yml up -d
          docker-compose -f docker-compose-03.yml down
          docker-compose -f docker-compose-03.yml up -d
          docker-compose -f docker-compose-demo.yml down
          docker-compose -f docker-compose-demo.yml up -d
          docker-compose -f docker-compose-dev.yml down
          docker-compose -f docker-compose-dev.yml up -d
