name: Deploy to Harbor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: |
          sudo docker build -t 192.168.3.81/dlink/test:latest -f docker-compose-03.yml .

      - name: Push to Harbor
        run: |
          sudo docker push 192.168.3.81/dlink/test:latest
